# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'designerhhtdMM.ui'
##
## Created by: Qt User Interface Compiler version 6.7.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QLabel, QLineEdit,
    QPushButton, QSizePolicy, QTabWidget, QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(815, 525)
        self.tabWidget = QTabWidget(Form)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 100, 821, 431))
        self.tabWidget.setStyleSheet(u"")
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.tabWidget_2 = QTabWidget(self.tab)
        self.tabWidget_2.setObjectName(u"tabWidget_2")
        self.tabWidget_2.setGeometry(QRect(-10, 0, 831, 401))
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.label_2 = QLabel(self.tab_3)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 60, 21, 16))
        font = QFont()
        font.setFamilies([u"Arial Rounded MT Bold"])
        font.setPointSize(14)
        font.setBold(False)
        self.label_2.setFont(font)
        self.txtA = QLineEdit(self.tab_3)
        self.txtA.setObjectName(u"txtA")
        self.txtA.setGeometry(QRect(50, 50, 61, 31))
        self.txtA.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.label_4 = QLabel(self.tab_3)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(130, 60, 21, 16))
        self.label_4.setFont(font)
        self.txtB = QLineEdit(self.tab_3)
        self.txtB.setObjectName(u"txtB")
        self.txtB.setGeometry(QRect(160, 50, 61, 31))
        self.txtB.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.label_5 = QLabel(self.tab_3)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(20, 120, 81, 16))
        self.label_5.setFont(font)
        self.txtFuncion = QLineEdit(self.tab_3)
        self.txtFuncion.setObjectName(u"txtFuncion")
        self.txtFuncion.setGeometry(QRect(110, 110, 121, 31))
        self.txtFuncion.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.label_6 = QLabel(self.tab_3)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(20, 170, 141, 16))
        self.label_6.setFont(font)
        self.txtTolerancia = QLineEdit(self.tab_3)
        self.txtTolerancia.setObjectName(u"txtTolerancia")
        self.txtTolerancia.setGeometry(QRect(160, 160, 71, 31))
        self.txtTolerancia.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.label_7 = QLabel(self.tab_3)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(20, 220, 151, 16))
        self.label_7.setFont(font)
        self.txtIteracion = QLineEdit(self.tab_3)
        self.txtIteracion.setObjectName(u"txtIteracion")
        self.txtIteracion.setGeometry(QRect(180, 210, 71, 31))
        self.txtIteracion.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.label_8 = QLabel(self.tab_3)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(490, 10, 131, 16))
        font1 = QFont()
        font1.setFamilies([u"Arial Rounded MT Bold"])
        font1.setPointSize(16)
        self.label_8.setFont(font1)
        self.label_9 = QLabel(self.tab_3)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(340, 50, 111, 16))
        self.label_9.setFont(font)
        self.label_10 = QLabel(self.tab_3)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(530, 50, 21, 16))
        self.label_10.setFont(font)
        self.label_11 = QLabel(self.tab_3)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(650, 50, 21, 16))
        self.label_11.setFont(font)
        self.label_12 = QLabel(self.tab_3)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(340, 120, 51, 16))
        self.label_12.setFont(font)
        self.label_13 = QLabel(self.tab_3)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(510, 120, 61, 16))
        self.label_13.setFont(font)
        self.txtIteracionFinal = QLineEdit(self.tab_3)
        self.txtIteracionFinal.setObjectName(u"txtIteracionFinal")
        self.txtIteracionFinal.setEnabled(False)
        self.txtIteracionFinal.setGeometry(QRect(460, 40, 51, 31))
        self.txtIteracionFinal.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.txtAFinal = QLineEdit(self.tab_3)
        self.txtAFinal.setObjectName(u"txtAFinal")
        self.txtAFinal.setEnabled(False)
        self.txtAFinal.setGeometry(QRect(560, 40, 81, 31))
        self.txtAFinal.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.txtBFinal = QLineEdit(self.tab_3)
        self.txtBFinal.setObjectName(u"txtBFinal")
        self.txtBFinal.setEnabled(False)
        self.txtBFinal.setGeometry(QRect(680, 40, 81, 31))
        self.txtBFinal.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.txtRaiz = QLineEdit(self.tab_3)
        self.txtRaiz.setObjectName(u"txtRaiz")
        self.txtRaiz.setEnabled(False)
        self.txtRaiz.setGeometry(QRect(390, 110, 111, 31))
        self.txtRaiz.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.txtError = QLineEdit(self.tab_3)
        self.txtError.setObjectName(u"txtError")
        self.txtError.setEnabled(False)
        self.txtError.setGeometry(QRect(570, 110, 111, 31))
        self.txtError.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.btnCalcular = QPushButton(self.tab_3)
        self.btnCalcular.setObjectName(u"btnCalcular")
        self.btnCalcular.setGeometry(QRect(50, 270, 111, 51))
        font2 = QFont()
        font2.setFamilies([u"Arial Rounded MT Bold"])
        font2.setPointSize(14)
        self.btnCalcular.setFont(font2)
        self.btnCalcular.setStyleSheet(u"background-color: rgb(107, 107, 107);")
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.tabWidget_3 = QTabWidget(self.tab_2)
        self.tabWidget_3.setObjectName(u"tabWidget_3")
        self.tabWidget_3.setGeometry(QRect(0, 0, 821, 411))
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.tabWidget_3.addTab(self.tab_5, "")
        self.tab_6 = QWidget()
        self.tab_6.setObjectName(u"tab_6")
        self.tabWidget_3.addTab(self.tab_6, "")
        self.tab_7 = QWidget()
        self.tab_7.setObjectName(u"tab_7")
        self.tabWidget_3.addTab(self.tab_7, "")
        self.tab_8 = QWidget()
        self.tab_8.setObjectName(u"tab_8")
        self.tabWidget_3.addTab(self.tab_8, "")
        self.tab_9 = QWidget()
        self.tab_9.setObjectName(u"tab_9")
        self.tabWidget_3.addTab(self.tab_9, "")
        self.tabWidget.addTab(self.tab_2, "")
        self.label = QLabel(Form)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(340, 10, 121, 51))
        font3 = QFont()
        font3.setFamilies([u"Tw Cen MT Condensed Extra Bold"])
        font3.setPointSize(20)
        self.label.setFont(font3)
        self.label.setCursor(QCursor(Qt.CursorShape.ArrowCursor))
        self.label.setFrameShadow(QFrame.Shadow.Plain)

        self.retranslateUi(Form)

        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.label_2.setText(QCoreApplication.translate("Form", u"A:", None))
        self.label_4.setText(QCoreApplication.translate("Form", u"B:", None))
        self.label_5.setText(QCoreApplication.translate("Form", u"Funci\u00f3n:", None))
        self.label_6.setText(QCoreApplication.translate("Form", u"Tolerancia (%):", None))
        self.label_7.setText(QCoreApplication.translate("Form", u"Max Iteraciones:", None))
        self.label_8.setText(QCoreApplication.translate("Form", u"Resultados:", None))
        self.label_9.setText(QCoreApplication.translate("Form", u"Iteraciones:", None))
        self.label_10.setText(QCoreApplication.translate("Form", u"A:", None))
        self.label_11.setText(QCoreApplication.translate("Form", u"B:", None))
        self.label_12.setText(QCoreApplication.translate("Form", u"Raiz:", None))
        self.label_13.setText(QCoreApplication.translate("Form", u"Error:", None))
        self.btnCalcular.setText(QCoreApplication.translate("Form", u"Calcular", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), QCoreApplication.translate("Form", u"M\u00e9todo Bisecci\u00f3n", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), QCoreApplication.translate("Form", u"M\u00e9todo regula falsi ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("Form", u"M\u00e9todos Cerrados", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_5), QCoreApplication.translate("Form", u"Punto Fijo", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_6), QCoreApplication.translate("Form", u"Newton Raphson", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_7), QCoreApplication.translate("Form", u"M\u00e9todo Secante", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_8), QCoreApplication.translate("Form", u"Secante Modificada", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_9), QCoreApplication.translate("Form", u"M\u00e9todo de Brent", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("Form", u"M\u00e9todos Abiertos", None))
        self.label.setText(QCoreApplication.translate("Form", u"PARCIAL 1", None))
    # retranslateUi

